server:
    port: 8010
    servlet:
        path: /
suntion:
    log:
        level: info
spring:
    application:
        name: suntion-auth
    datasource:
        druid:
            min-idle: 0
            db-type: com.alibaba.druid.pool.DruidDataSource
            max-active: 20
            time-between-eviction-runs-millis: 60000
            remove-abandoned: true
            log-abandoned: true
            remove-abandoned-timeout-millis: 1800
            filters: stat
            initial-size: 5
            min-evictable-idle-time-millis: 300000
            max-wait: 60000
            url: jdbc:mysql://sontion.cn:3306/auth-dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
            username: root
            password: rootabc,123
    quartz:
        job-store-type: jdbc
        properties:
            org: null
            quartz:
                scheduler:
                    instanceId: AUTO
                    instanceName: suntion_clusteredScheduler
                    skipUpdateCheck: true
                jobStore:
                    txIsolationLevelSerializable: false
                    useProperties: false
                    isClustered: true
                    tablePrefix: QRTZ_
                    misfireThreshold: 5000
                    class: org.quartz.impl.jdbcjobstore.JobStoreTX
                    clusterCheckinInterval: 10000
                    driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                threadPool:
                    threadCount: 50
                    threadPriority: 5
                    class: org.quartz.simpl.SimpleThreadPool
                    threadsInheritContextClassLoaderOfInitializingThread: true
    redis:
        host: 47.106.122.50
        port: 6379
        password: rootabc,123
        database: 0
        jedis:
            pool:
                max-idle: 200
                min-idle: 20
                max-active: 2000
                max-wait: 1000
        timeout: 50000
mybatis-plus:
    mapper-locations[0]: classpath*:/mapper/**/*Mapper.xml
eureka:
    client:
        service-url:
            defaultZone: http://suntion.cc:8101/eureka
feign:
    hystrix:
        enabled: true
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 5000
ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 5000
